name: rtai-project
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy==1.26.0
  - pytorch==2.1.2
  - torchvision==0.16.2
  - scipy==1.11.1
  - cpuonly
  - matplotlib